### ISSUE TITLE
error

### ISSUE THREAD

**Issue by schokk89** [Navid2zp/hcloud-tg#1]
I can't start. Entered all the necessary data
![Снимок экрана 2021-02-28 08:04:53](https://user-images.githubusercontent.com/4554835/109408817-26579600-799e-11eb-8f0c-afb4e5cb6ae6.png)

$ python3 bot.py                                                                                                                                1 ⨯
Allowed users:
Bot configured ...
Running the bot ...
Traceback (most recent call last):
  File "/home/max/hcloud-tg/bot.py", line 19, in <module>
    handler = BotHandler()
  File "/home/max/hcloud-tg/hcloud_tgbot/handlers.py", line 22, in __init__
    self.updater = Updater(token=config.BOT_TOKEN, use_context=True)
  File "/home/max/.local/lib/python3.9/site-packages/telegram/ext/updater.py", line 137, in __init__
    raise ValueError('`token` or `bot` must be passed')
ValueError: `token` or `bot` must be passed

**Comment by Navid2zp** [comment]
You need to set `BOT_TOKEN`, `HETZNER_API_KEY` and `ALLOWED_USERS` as environment variables in order for the script to use it.

You're setting those directly in the code which then script overrides when starting.

Now if you really want to do it this way, then you should comment out lines 10, 14 and 18 so the overrides won't happen but it's not a good idea to store your API keys in the.
